"use strict";
const stage=document.getElementById("stage"),profOnStage=document.getElementById("profOnStage"),operatorOnStage=document.getElementById("operatorOnStage"),box=document.getElementById("box"),burst=document.getElementById("burst"),finalMessage=document.getElementById("finalMessage"),statusEl=document.getElementById("status"),resetBtn=document.getElementById("reset"),finalShowBtn=document.getElementById("finalShow"),heehee=document.getElementById("heehee");
const professorCards=[...document.querySelectorAll("[data-prof]")],operatorCards=[...document.querySelectorAll("[data-op]")];
let selectedProfessor=1,selectedOperator=1,busy=false;
const positions={1:[23,21.3,8.7,12.5,"green"],2:[31.8,21.3,8.7,12.5,"green"],3:[40.7,21.3,8.7,12.5,"green"],5:[23,34,8.7,12.5,"green"],6:[31.8,34,8.7,12.5,"green"],7:[40.7,34,8.7,12.5,"green"],9:[23,46.8,8.7,12.5,"green"],10:[31.8,46.8,8.7,12.5,"green"],11:[40.7,46.8,8.7,12.5,"green"],13:[23,59.7,8.7,12.5,"red"],14:[31.8,59.7,8.7,12.5,"red"],15:[40.7,59.7,8.7,12.5,"red"],4:[56.1,23.8,8.3,11.5,"red"],8:[56.1,36.8,8.3,11.5,"red"],12:[56.1,49.7,8.3,11.5,"red"],16:[56.1,62.5,8.3,11.5,"red"]};
function mark(cards,key,index){cards.forEach(c=>c.classList.toggle("selected",Number(c.dataset[key])===index));}
professorCards.forEach(card=>card.addEventListener("click",()=>{if(busy)return;selectedProfessor=Number(card.dataset.prof);mark(professorCards,"prof",selectedProfessor);profOnStage.src=card.querySelector("img").src;resetProfessor();statusEl.textContent=`Profesor ${selectedProfessor} seleccionado`;}));
operatorCards.forEach(card=>card.addEventListener("click",()=>{selectedOperator=Number(card.dataset.op);mark(operatorCards,"op",selectedOperator);operatorOnStage.src=card.querySelector("img").src;statusEl.textContent=`Operador ${selectedOperator} seleccionado`;}));
function resetProfessor(){profOnStage.getAnimations().forEach(a=>a.cancel());Object.assign(profOnStage.style,{display:"block",opacity:"1",left:"56.2%",top:"17.5%",transform:"translate(0,0) rotate(0deg) scale(1)"});}
async function playOnce(){try{heehee.pause();heehee.currentTime=0;await heehee.play();}catch(e){console.warn(e);}}
async function launchProfessor(n){if(busy)return;busy=true;statusEl.textContent=`Lanzamiento activado por ${n}`;resetProfessor();burst.style.display="block";await playOnce();const a=profOnStage.animate([{transform:"translate(0,0) rotate(0deg) scale(1)",opacity:1},{transform:"translate(4vw,-5vh) rotate(30deg) scale(1.04)",opacity:1,offset:.2},{transform:"translate(14vw,-14vh) rotate(160deg) scale(.9)",opacity:1,offset:.5},{transform:"translate(32vw,-34vh) rotate(520deg) scale(.45)",opacity:0}],{duration:3200,easing:"cubic-bezier(.18,.65,.25,1)",fill:"forwards"});await a.finished;burst.style.display="none";setTimeout(()=>{resetProfessor();statusEl.textContent="Profesor nuevamente en la posición 4";busy=false;},500);}
async function moveBox(n,r){if(busy)return;busy=true;statusEl.textContent=`Moviendo caja a ${n}`;Object.assign(box.style,{display:"block",left:"68%",top:"13%"});const l=r[0]+r[2]/2-2.5,t=r[1]+r[3]/2-3;const a=box.animate([{left:"68%",top:"13%"},{left:"52%",top:"20%",offset:.45},{left:l+"%",top:t+"%"}],{duration:1500,easing:"ease-in-out",fill:"forwards"});await a.finished;box.style.left=l+"%";box.style.top=t+"%";statusEl.textContent=`Caja ubicada en ${n}`;busy=false;}
Object.entries(positions).forEach(([n,r])=>{const b=document.createElement("button");b.className="hit";b.type="button";b.ariaLabel="Posición "+n;Object.assign(b.style,{left:r[0]+"%",top:r[1]+"%",width:r[2]+"%",height:r[3]+"%"});b.addEventListener("click",()=>r[4]==="red"?launchProfessor(n):moveBox(n,r));stage.appendChild(b);});
function playTwice(){const a=heehee.cloneNode(true),b=heehee.cloneNode(true);a.volume=b.volume=1;a.play().catch(()=>{});setTimeout(()=>b.play().catch(()=>{}),900);}
async function runFinal(){if(busy)return;busy=true;statusEl.textContent="Mostrando a todos";box.style.display="none";finalMessage.style.display="block";const imgs=[...professorCards,...operatorCards].map(c=>c.querySelector("img").src),spots=[[8,55],[18,60],[28,57],[38,61],[48,56],[58,60],[68,56],[76,61],[84,57]],els=imgs.map((src,i)=>{const el=document.createElement("img");el.className="final-character";el.src=src;el.style.left=spots[i][0]+"%";el.style.top=spots[i][1]+"%";stage.appendChild(el);return el;});await new Promise(r=>setTimeout(r,1400));playTwice();statusEl.textContent="¡Todos salen volando!";await Promise.all(els.map((el,i)=>{const d=i%2===0?1:-1,x=d*(18+i*3),y=-(28+(i%4)*7),s=d*(420+i*85);return el.animate([{transform:"translate(0,0) rotate(0deg) scale(1)",opacity:1},{transform:`translate(${d*3}vw,-4vh) rotate(${d*25}deg) scale(1.05)`,opacity:1,offset:.18},{transform:`translate(${x*.5}vw,${y*.55}vh) rotate(${s*.45}deg) scale(.85)`,opacity:1,offset:.6},{transform:`translate(${x}vw,${y}vh) rotate(${s}deg) scale(.35)`,opacity:0}],{duration:3600,delay:i*110,easing:"cubic-bezier(.16,.7,.25,1)",fill:"forwards"}).finished;}));els.forEach(e=>e.remove());finalMessage.style.display="none";resetProfessor();statusEl.textContent="Gran final completado";busy=false;}
finalShowBtn.addEventListener("click",runFinal);
resetBtn.addEventListener("click",()=>{busy=false;heehee.pause();heehee.currentTime=0;box.style.display="none";burst.style.display="none";finalMessage.style.display="none";document.querySelectorAll(".final-character").forEach(e=>e.remove());resetProfessor();operatorOnStage.src=`img/operadores/operador${selectedOperator}.png`;statusEl.textContent="Dashboard reiniciado";});
